### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by arb** [continuationlabs/hapchat#30]
What are we doing with the DB? Currently, we aren't doing anything with it and it's just adding complexity. We should either:
1. Use the DB completely and even store image information in there
2. Cut the DB out entirely for version 1

@nvcexploder can you weigh in on this?

**Comment by jaw187** [comment]
Cut it out.
On Oct 19, 2014 3:26 PM, "Adam Bretz" notifications@github.com wrote:

What are we doing with the DB? Currently, we aren't doing anything with it
and it's just adding complexity. We should either:
1. Use the DB completely and even store image information in there
2. Cut the DB out entirely for version 1

—
Reply to this email directly or view it on GitHub
https://github.com/nvcexploder/hapchat/issues/30.

**Comment by nvcexploder** [comment]
agreed.
