### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by arb** [continuationlabs/hapchat#4]
Add routes for
- ~~static content~~
- ~~something to alert me when there are new pictures? (socket)~~
- logging in (with proper status codes and redirects)
- ~~a way to upload new pictures that should stream from hapchat to the "cdn" server~~

**Comment by jaw187** [comment]
Logging in route will be addressed by Bell.

**Comment by jaw187** [comment]
@arb Ok to close since auth plugin will address logging in?
