### ISSUE TITLE
Huh?

### ISSUE THREAD

**Issue by hueniverse** [continuationlabs/hapchat#64]
What is this repo for? Is it still being used?

**Comment by Marsup** [comment]
I think it was created for hapidays. Probably a reference for people seeing the conference and want the code.

**Comment by arb** [comment]
It was what we talked about at Empire Node last year.

**Comment by hueniverse** [comment]
Pick one:
- Delete it
- Mark it as no longer maintained
- Update the readme so that people know what it is for and how to use it
